# Generated by Django 4.2.30 on 2026-06-25 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('DESCANSO_INICIO', 'Inicio Descanso'), ('DESCANSO_FIN', 'Fin Descanso')], max_length=15, verbose_name='tipo de marcaje')),
                ('fecha_hora', models.DateTimeField(verbose_name='fecha y hora')),
                ('ip_address', models.GenericIPAddressField(verbose_name='dirección IP')),
                ('validado', models.BooleanField(default=False, verbose_name='validado')),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marcajes', to=settings.AUTH_USER_MODEL, verbose_name='operario')),
            ],
            options={
                'verbose_name': 'marcaje',
                'verbose_name_plural': 'marcajes',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_base_mensual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='salario base mensual')),
                ('porcentaje_ss_patronal', models.DecimalField(decimal_places=2, default=31.5, max_digits=5, verbose_name='% SS patronal')),
                ('operario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='configuracion_nomina', to=settings.AUTH_USER_MODEL, verbose_name='operario')),
            ],
            options={
                'verbose_name': 'configuración de nómina',
                'verbose_name_plural': 'configuraciones de nómina',
            },
        ),
    ]
