# Generated by Django 4.2.30 on 2026-06-25 20:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='número')),
                ('fecha', models.DateField(verbose_name='fecha del asiento')),
                ('concepto', models.CharField(max_length=500, verbose_name='concepto')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('POSTEADO', 'Posteado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=10, verbose_name='estado')),
                ('tipo_documento', models.CharField(blank=True, max_length=50, verbose_name='tipo de documento')),
                ('documento_id', models.IntegerField(blank=True, null=True, verbose_name='ID del documento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'asiento contable',
                'verbose_name_plural': 'asientos contables',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('tipo', models.CharField(choices=[('A', 'Activo'), ('P', 'Pasivo'), ('NP', 'Neto Patrimonio'), ('I', 'Ingresos'), ('G', 'Gastos')], max_length=2, verbose_name='tipo')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='saldo')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='accounting.cuentacontable', verbose_name='cuenta padre')),
            ],
            options={
                'verbose_name': 'cuenta contable',
                'verbose_name_plural': 'cuentas contables',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='PlanContableDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='debe')),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='haber')),
                ('descripcion', models.CharField(blank=True, max_length=500, verbose_name='descripción')),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='accounting.asientocontable', verbose_name='asiento')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='accounting.cuentacontable', verbose_name='cuenta')),
            ],
            options={
                'verbose_name': 'movimiento contable',
                'verbose_name_plural': 'movimientos contables',
            },
        ),
    ]
