# Generated by Django 4.2.30 on 2026-06-25 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarantiaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(choices=[('PARTICULAR', 'Particular (B2C) - 12 meses'), ('EMPRESA', 'Empresa/Autónomo (B2B) - 6 meses')], max_length=15, verbose_name='tipo de cliente')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha de fin')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garantia', to='sales.ventavehiculo', verbose_name='venta')),
            ],
            options={
                'verbose_name': 'garantía de vehículo',
                'verbose_name_plural': 'garantías de vehículos',
            },
        ),
        migrations.CreateModel(
            name='HistorialReparacionGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso_taller', models.DateField(verbose_name='fecha de ingreso')),
                ('descripcion_averia', models.TextField(verbose_name='descripción de la avería')),
                ('estado', models.CharField(choices=[('ESTUDIO', 'En Evaluación'), ('PROCESO', 'En Reparación'), ('CERRADO', 'Entregado')], default='ESTUDIO', max_length=15, verbose_name='estado')),
                ('costo_repuestos_interno', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='coste repuestos (interno)')),
                ('costo_mano_obra_interno', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='coste mano de obra (interno)')),
                ('total_costo_reparacion', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='coste total reparación')),
                ('fecha_resolucion', models.DateField(blank=True, null=True, verbose_name='fecha de resolución')),
                ('garantia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparaciones', to='warranty.garantiavehiculo', verbose_name='garantía')),
            ],
            options={
                'verbose_name': 'reparación en garantía',
                'verbose_name_plural': 'reparaciones en garantía',
                'ordering': ['-fecha_ingreso_taller'],
            },
        ),
    ]
