# Generated by Django 4.2.30 on 2026-07-03 15:04

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoEstructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateField(verbose_name='fecha de factura')),
                ('proveedor_acreedor', models.CharField(max_length=150, verbose_name='proveedor/acreedor')),
                ('cif_nif', models.CharField(max_length=15, verbose_name='CIF/NIF')),
                ('categoria', models.CharField(choices=[('ARRENDAMIENTO', 'Alquiler del Galpón (Cuenta PGC 621)'), ('SUMINISTROS', 'Luz, Agua, Conectividad (Cuenta PGC 628)'), ('LIMPIEZA_PROD', 'Productos de Limpieza e Insumos Globales (Cuenta PGC 602)'), ('LIMPIEZA_SERV', 'Servicios de Empresa de Limpieza Externa (Cuenta PGC 629)'), ('NOMINAS_ESTR', 'Salarios Personal Limpieza/Admin (Cuenta PGC 640)'), ('SEG_SOCIAL_ESTR', 'Aportes Patronales Personal Estructura (Cuenta PGC 642)'), ('IMPUESTOS_ESTR', 'IBI, Tasas Municipales, Vados (Cuenta PGC 631)'), ('OTROS', 'Otros gastos no especificados')], max_length=20, verbose_name='categoría')),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='base imponible')),
                ('tipo_iva', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=4, verbose_name='tipo de IVA (%)')),
                ('cuota_iva', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12, verbose_name='cuota IVA')),
                ('retencion_irpf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='retención IRPF (%)')),
                ('cuota_retencion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='cuota retención')),
                ('total_factura', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12, verbose_name='total factura')),
                ('documento_pdf', models.FileField(blank=True, null=True, upload_to='facturas_gastos/', verbose_name='factura PDF')),
                ('pagado', models.BooleanField(default=False, verbose_name='pagado')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='fecha de pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'gasto de estructura',
                'verbose_name_plural': 'gastos de estructura',
                'ordering': ['-fecha_factura', '-created_at'],
            },
        ),
    ]
