# Generated by Django 6.0.7 on 2026-07-20 01:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InversionInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(verbose_name='fecha de emisión')),
                ('proveedor_acreedor', models.CharField(max_length=150, verbose_name='proveedor/acreedor')),
                ('numero_factura', models.CharField(max_length=50, verbose_name='número de factura')),
                ('total_factura_fisico', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total factura físico (€)')),
                ('documento_pdf', models.FileField(blank=True, null=True, upload_to='facturas_gastos/', verbose_name='factura PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inversiones_iniciales', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('forma_pago', models.ForeignKey(limit_choices_to={'codigo__in': ['570', '572']}, on_delete=django.db.models.deletion.PROTECT, related_name='inversiones_forma_pago', to='accounting.cuentacontable', verbose_name='forma de pago (banco)')),
            ],
            options={
                'verbose_name': 'inversión inicial',
                'verbose_name_plural': 'inversiones iniciales',
                'ordering': ['-fecha_emision', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LineaInversionInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('HERRAMIENTAS', 'Herramientas / Utillaje (Cuenta PGC 214)'), ('MOBILIARIO', 'Mobiliario (Cuenta PGC 216)'), ('INFORMATICA', 'Informática (Cuenta PGC 217)'), ('ALQUILER', 'Alquiler del local (Cuenta PGC 621)'), ('NOTARIA', 'Notaría / Registro (Cuenta PGC 622)'), ('TASAS', 'Tasas y permisologías (Cuenta PGC 631)'), ('OTROS', 'Otros gastos de apertura')], max_length=20, verbose_name='categoría')),
                ('concepto', models.CharField(max_length=255, verbose_name='concepto/descripción')),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='base imponible (€)')),
                ('tipo_iva', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=4, verbose_name='tipo de IVA (%)')),
                ('cuota_iva', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12, verbose_name='cuota IVA')),
                ('total_linea', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12, verbose_name='total línea')),
                ('inversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='expenses.inversioninicial', verbose_name='inversión')),
            ],
            options={
                'verbose_name': 'línea de inversión',
                'verbose_name_plural': 'líneas de inversión',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=10, verbose_name='cuenta PGC')),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripción')),
                ('valor_adquisicion', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor de adquisición (€)')),
                ('fecha_adquisicion', models.DateField(verbose_name='fecha de adquisición')),
                ('vida_util_anos', models.IntegerField(default=10, verbose_name='vida útil (años)')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('linea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activo_fijo', to='expenses.lineainversioninicial', verbose_name='línea de inversión')),
            ],
            options={
                'verbose_name': 'activo fijo',
                'verbose_name_plural': 'activos fijos',
                'ordering': ['-fecha_adquisicion'],
            },
        ),
        migrations.CreateModel(
            name='AmortizacionAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(verbose_name='año')),
                ('cuota', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cuota anual (€)')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortizaciones', to='expenses.activofijo', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'amortización anual',
                'verbose_name_plural': 'amortizaciones anuales',
                'ordering': ['año'],
                'unique_together': {('activo', 'año')},
            },
        ),
    ]
