# Generated by Django 6.0.7 on 2026-07-31 20:18

import apps.expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_inversioninicial_lineainversioninicial_activofijo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversioninicial',
            name='documento_pdf',
            field=models.FileField(blank=True, null=True, upload_to=apps.expenses.models._ruta_documento_inversion, verbose_name='factura PDF'),
        ),
    ]
