# Generated by Django 6.0.7 on 2026-08-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_inversioninicial_documento_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoestructura',
            name='categoria',
            field=models.CharField(choices=[('ARRENDAMIENTO', 'Alquiler del Galpón (Cuenta PGC 621)'), ('SUMINISTROS', 'Luz, Agua, Conectividad (Cuenta PGC 628)'), ('LIMPIEZA_PROD', 'Productos de Limpieza e Insumos Globales (Cuenta PGC 602)'), ('LIMPIEZA_SERV', 'Servicios de Empresa de Limpieza Externa (Cuenta PGC 629)'), ('IMPUESTOS_ESTR', 'IBI, Tasas Municipales, Vados (Cuenta PGC 631)'), ('OTROS', 'Otros gastos no especificados')], max_length=20, verbose_name='categoría'),
        ),
    ]
