# Generated by Django 5.0.14 on 2026-08-12 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_add_pgc_accounts_bank'),
        ('expenses', '0004_alter_gastoestructura_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoestructura',
            name='forma_pago',
            field=models.ForeignKey(blank=True, limit_choices_to={'codigo__in': ['570', '572']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_forma_pago', to='accounting.cuentacontable', verbose_name='cuenta de pago (banco/caja)'),
        ),
    ]
