# Generated by Django 6.0.7 on 2026-08-05 15:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_add_pgc_accounts_bank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NominaEstructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nomina', models.DateField(verbose_name='fecha de nómina')),
                ('salario_bruto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='salario bruto (640)')),
                ('ss_patronal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='SS patronal (642)')),
                ('retencion_irpf', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='retención IRPF (4751)')),
                ('ss_obrera', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='SS obrera (476)')),
                ('liquido_percibir', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='líquido a percibir (465)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asiento_contable', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomina_estructura', to='accounting.asientocontable', verbose_name='asiento contable')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominas_estructura_creadas', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominas_estructura', to=settings.AUTH_USER_MODEL, verbose_name='empleado')),
            ],
            options={
                'verbose_name': 'nómina de estructura',
                'verbose_name_plural': 'nóminas de estructura',
                'ordering': ['-fecha_nomina', '-created_at'],
            },
        ),
    ]
