# Generated by Django 4.2.30 on 2026-06-25 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('unidad', models.CharField(max_length=20, verbose_name='unidad de medida')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='stock actual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='stock mínimo de seguridad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='precio unitario')),
                ('alerta_stock', models.BooleanField(default=False, verbose_name='alerta de stock bajo')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='estado')),
                ('horas_estimadas', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='horas estimadas')),
                ('horas_reales', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='horas reales')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='fecha de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ots_creadas', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to=settings.AUTH_USER_MODEL, verbose_name='operario')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='vehicles.vehiculo', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'orden de trabajo',
                'verbose_name_plural': 'órdenes de trabajo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='cantidad')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='workshop.material', verbose_name='material')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_usados', to='workshop.ordentrabajo', verbose_name='orden de trabajo')),
            ],
            options={
                'verbose_name': 'material usado',
                'verbose_name_plural': 'materiales usados',
                'unique_together': {('orden_trabajo', 'material')},
            },
        ),
    ]
