# Generated by Django 6.0.7 on 2026-07-18 01:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('workshop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='precio unitario')),
                ('fecha_compra', models.DateField(verbose_name='fecha de compra')),
                ('proveedor', models.CharField(max_length=150, verbose_name='proveedor')),
                ('cif_nif', models.CharField(max_length=15, verbose_name='CIF/NIF')),
                ('tipo_inventario', models.CharField(choices=[('300', 'Compras (Grupo 3 - Existencias)'), ('310', 'Mercaderías (A)'), ('320', 'Materias primas (A)'), ('330', 'Otros aprovisionamientos (A)')], default='300', max_length=3, verbose_name='cuenta de inventario')),
                ('base_imponible', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12, verbose_name='base imponible')),
                ('tipo_iva', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=4, verbose_name='tipo de IVA (%)')),
                ('cuota_iva', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12, verbose_name='cuota IVA')),
                ('documento_pdf', models.FileField(blank=True, null=True, upload_to='facturas_gastos/', verbose_name='factura PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asiento_contable', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compra_material', to='accounting.asientocontable', verbose_name='asiento contable')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_material_creadas', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='workshop.material', verbose_name='material')),
            ],
            options={
                'verbose_name': 'compra de material',
                'verbose_name_plural': 'compras de material',
                'ordering': ['-fecha_compra', '-created_at'],
            },
        ),
    ]
