# Generated by Django 6.0.7 on 2026-07-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_compramaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compramaterial',
            name='numero_factura',
            field=models.CharField(blank=True, help_text='Permite agrupar varias compras (materiales) de la misma factura de proveedor.', max_length=50, verbose_name='número de factura'),
        ),
    ]
