# Generated by Django 6.0.7 on 2026-07-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_compramaterial_numero_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compramaterial',
            name='tipo_inventario',
            field=models.CharField(choices=[('310', 'Mercaderías (A)'), ('320', 'Materias primas (A)'), ('330', 'Otros aprovisionamientos (A)'), ('300', 'Compras (Grupo 3)')], default='310', max_length=3, verbose_name='cuenta de inventario'),
        ),
    ]
