# Generated by Django 5.0.14 on 2026-08-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_alter_compramaterial_tipo_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compramaterial',
            name='tipo_inventario',
            field=models.CharField(choices=[('300', 'Compras (Grupo 3)'), ('310', 'Mercaderías (A)'), ('320', 'Materias primas (A)'), ('330', 'Otros aprovisionamientos (A)')], default='300', max_length=3, verbose_name='cuenta de inventario'),
        ),
    ]
