# Generated by Django 5.2.15 on 2026-07-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='puede_eliminar',
            field=models.BooleanField(default=True, verbose_name='puede eliminar registros'),
        ),
    ]
