# Generated by Django 6.0.7 on 2026-07-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_puede_eliminar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('OPERARIO', 'Operario de Taller'), ('VENDEDOR', 'Vendedor'), ('GESTORIA', 'Gestoría Externa')], default='ADMIN', max_length=20, verbose_name='rol'),
        ),
    ]
