# Generated by Django 4.2.30 on 2026-06-25 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=7, unique=True, verbose_name='matrícula')),
                ('bastidor', models.CharField(max_length=17, unique=True, verbose_name='bastidor/VIN')),
                ('marca', models.CharField(max_length=50, verbose_name='marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='modelo')),
                ('anio', models.IntegerField(verbose_name='año')),
                ('combustible', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Diésel'), ('HIBRIDO', 'Híbrido'), ('ELECTRICO', 'Eléctrico'), ('GAS_LPG', 'Gas (LPG)'), ('GAS_CNG', 'Gas (CNG)')], max_length=20, verbose_name='combustible')),
                ('kilometraje', models.IntegerField(verbose_name='kilometraje')),
                ('tipo_dano', models.CharField(choices=[('ACCIDENTAL', 'Accidental'), ('INUNDACION', 'Daños por Inundación'), ('GRANIZO', 'Daños por Granizo'), ('INCENDIO', 'Daños por Incendio'), ('MECANICO', 'Daño Mecánico'), ('OTRO', 'Otro')], max_length=20, verbose_name='tipo de daño')),
                ('estado', models.CharField(choices=[('ADQUIRIDO', 'Adquirido'), ('TALLER', 'En Taller'), ('ACONDICIONADO', 'Acondicionado'), ('EN_VENTA', 'En Venta'), ('VENDIDO', 'Vendido')], default='ADQUIRIDO', max_length=20, verbose_name='estado')),
                ('etiqueta_ambiental', models.CharField(choices=[('0', 'Cero emisiones (0)'), ('ECO', 'ECO'), ('B', 'B'), ('C', 'C')], default='C', max_length=5, verbose_name='etiqueta ambiental')),
                ('fecha_adquisicion', models.DateField(verbose_name='fecha de adquisición')),
                ('plataforma_subasta', models.CharField(blank=True, max_length=100, verbose_name='plataforma de subasta')),
                ('precio_subasta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio de adjudicación')),
                ('tasas_sala', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='tasas de la sala')),
                ('logistica_grua', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='logística/grúa')),
                ('coste_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='coste inicial total')),
                ('descripcion_dano', models.TextField(blank=True, verbose_name='descripción del daño')),
                ('imagen_principal', models.ImageField(blank=True, upload_to='vehiculos/', verbose_name='imagen principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'vehículo',
                'verbose_name_plural': 'vehículos',
                'ordering': ['-fecha_adquisicion', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagenVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='vehiculos/', verbose_name='imagen')),
                ('es_principal', models.BooleanField(default=False, verbose_name='es imagen principal')),
                ('orden', models.IntegerField(default=0, verbose_name='orden')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='vehicles.vehiculo', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'imagen de vehículo',
                'verbose_name_plural': 'imágenes de vehículos',
                'ordering': ['orden'],
            },
        ),
    ]
