# Generated by Django 4.2.30 on 2026-06-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='plataforma_subasta',
            field=models.CharField(blank=True, choices=[('', '---------'), ('BCA', 'BCA (British Car Auctions)'), ('COPART', 'Copart'), ('ADESA', 'ADESA'), ('KBC', 'KBC'), ('AUTOVIAS', 'Autovias'), ('SUBASTAS_RED', 'Subastas Red'), ('MANNHEIM', 'Mannheim'), ('EURODAM', 'Eurodam'), ('OTRO', 'Otro')], max_length=100, verbose_name='plataforma de subasta'),
        ),
    ]
