# Generated by Django 4.2.30 on 2026-06-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehiculo_plataforma_subasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio de venta'),
        ),
    ]
