# Generated by Django 6.0.7 on 2026-07-27 15:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_add_pgc_accounts_bank'),
        ('vehicles', '0003_vehiculo_precio_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='asiento_contable',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculo_compra', to='accounting.asientocontable', verbose_name='asiento contable'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='base_imponible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='base imponible'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='cif_nif',
            field=models.CharField(blank=True, max_length=15, verbose_name='CIF/NIF proveedor'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='cuota_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='cuota IVA'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='factura_compra_pdf',
            field=models.FileField(blank=True, upload_to='facturas_compra/', verbose_name='factura de compra (PDF)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='forma_pago',
            field=models.ForeignKey(blank=True, limit_choices_to={'codigo__startswith': '572'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_pago', to='accounting.cuentacontable', verbose_name='forma de pago (cuenta bancaria 572)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50, verbose_name='nº factura de compra'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='proveedor',
            field=models.CharField(blank=True, help_text='Nombre del proveedor o casa de subastas', max_length=150, verbose_name='proveedor / subasta'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='0 si la subasta no factura IVA, 21 si aplica', max_digits=4, verbose_name='tipo de IVA (%)'),
        ),
    ]
