# Generated by Django 6.0.7 on 2026-07-27 23:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehiculo_asiento_contable_vehiculo_base_imponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Importe del IVA facturado. 0 si no factura IVA', max_digits=12, verbose_name='IVA soportado (€)'),
        ),
    ]
