# Generated by Django 6.0.7 on 2026-08-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_rename_base_imponible_to_coste_total_adquisicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='coste_total_adquisicion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='coste total de adquisición'),
        ),
    ]
