# Generated by Django 6.0.7 on 2026-07-21 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('sales', '0005_alter_costoacondicionamiento_id_alter_detallerebu_id_and_more'),
        ('vehicles', '0003_vehiculo_precio_venta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: BBVA Empresa', max_length=100, verbose_name='nombre')),
                ('iban', models.CharField(max_length=34, unique=True, verbose_name='IBAN')),
                ('swift', models.CharField(blank=True, max_length=11, verbose_name='SWIFT/BIC')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuenta_contable', models.ForeignKey(limit_choices_to={'codigo__startswith': '572'}, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancarias', to='accounting.cuentacontable', verbose_name='cuenta contable (572)')),
            ],
            options={
                'verbose_name': 'cuenta bancaria',
                'verbose_name_plural': 'cuentas bancarias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='BancoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('fecha_valor', models.DateField(blank=True, null=True, verbose_name='fecha de valor')),
                ('concepto', models.CharField(max_length=255, verbose_name='concepto')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso / Cobro'), ('EGRESO', 'Egreso / Pago')], max_length=10, verbose_name='tipo')),
                ('importe', models.DecimalField(decimal_places=2, help_text='Valor absoluto', max_digits=12, verbose_name='importe')),
                ('conciliado', models.BooleanField(default=False, verbose_name='conciliado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asiento_asociado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimiento_banco', to='accounting.asientocontable', verbose_name='asiento contable')),
                ('banco_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='bank.bancocuenta', verbose_name='cuenta bancaria')),
                ('vehiculo_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_banco', to='vehicles.vehiculo', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'movimiento bancario',
                'verbose_name_plural': 'movimientos bancarios',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=150, verbose_name='nombre del cliente')),
                ('cliente_dni', models.CharField(max_length=9, verbose_name='DNI/NIE')),
                ('fecha_reserva', models.DateField(verbose_name='fecha de reserva')),
                ('importe_reserva', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='importe de la reserva')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CONVERTIDA', 'Convertida en Venta'), ('DEVUELTA', 'Devuelta al cliente'), ('PENALIZADA', 'Penalización (S.L. retiene)')], default='ACTIVA', max_length=15, verbose_name='estado')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banco_movimiento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reserva', to='bank.bancomovimiento', verbose_name='movimiento bancario')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='vehicles.vehiculo', verbose_name='vehículo')),
                ('venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserva', to='sales.ventavehiculo', verbose_name='venta asociada')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-fecha_reserva'],
            },
        ),
        migrations.AddIndex(
            model_name='bancomovimiento',
            index=models.Index(fields=['fecha', 'importe', 'tipo'], name='bank_bancom_fecha_c048ec_idx'),
        ),
        migrations.AddIndex(
            model_name='bancomovimiento',
            index=models.Index(fields=['conciliado', 'fecha'], name='bank_bancom_concili_7b89ab_idx'),
        ),
        migrations.AddIndex(
            model_name='bancomovimiento',
            index=models.Index(fields=['banco_cuenta', 'fecha'], name='bank_bancom_banco_c_1e8062_idx'),
        ),
    ]
