# Generated by Django 6.0.7 on 2026-07-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancocuenta',
            name='soporte_deposito',
            field=models.FileField(blank=True, upload_to='banco/soportes/', verbose_name='soporte del deposito inicial'),
        ),
        migrations.AddField(
            model_name='bancomovimiento',
            name='notas',
            field=models.TextField(blank=True, verbose_name='notas'),
        ),
        migrations.AddField(
            model_name='bancomovimiento',
            name='soporte',
            field=models.FileField(blank=True, upload_to='banco/movimientos/', verbose_name='soporte'),
        ),
    ]
