# Generated by Django 4.2.30 on 2026-06-25 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(choices=[('PARTICULAR', 'Particular (B2C)'), ('EMPRESA', 'Empresa/Autónomo (B2B)')], max_length=15, verbose_name='tipo de cliente')),
                ('cliente_nombre', models.CharField(max_length=200, verbose_name='nombre del cliente')),
                ('cliente_dni', models.CharField(max_length=9, verbose_name='DNI/NIE')),
                ('cliente_direccion', models.TextField(verbose_name='dirección')),
                ('cliente_poblacion', models.CharField(max_length=100, verbose_name='población')),
                ('cliente_provincia', models.CharField(max_length=100, verbose_name='provincia')),
                ('cliente_cp', models.CharField(max_length=5, verbose_name='código postal')),
                ('cliente_telefono', models.CharField(max_length=15, verbose_name='teléfono')),
                ('cliente_email', models.EmailField(max_length=254, verbose_name='email')),
                ('fecha_venta', models.DateField(verbose_name='fecha de venta')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('FINANCIADO', 'Financiado'), ('MIXTO', 'Mixto')], max_length=20, verbose_name='método de pago')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio de venta')),
                ('coste_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='coste total del vehículo')),
                ('margen_porcentaje', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='margen de ganancia %')),
                ('base_imponible', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='base imponible (margen)')),
                ('cuota_iva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cuota IVA REBU')),
                ('contrato_pdf', models.FileField(blank=True, upload_to='contratos/', verbose_name='contrato de compraventa')),
                ('mandato_pdf', models.FileField(blank=True, upload_to='mandatos/', verbose_name='mandato de gestoría')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='venta', to='vehicles.vehiculo', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'venta de vehículo',
                'verbose_name_plural': 'ventas de vehículos',
                'ordering': ['-fecha_venta'],
            },
        ),
    ]
