# Generated by Django 4.2.30 on 2026-07-06 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventavehiculo',
            name='asiento_contable',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta', to='accounting.asientocontable', verbose_name='asiento contable'),
        ),
    ]
