# Generated by Django 6.0.7 on 2026-07-21 15:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
        ('sales', '0005_alter_costoacondicionamiento_id_alter_detallerebu_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventavehiculo',
            name='pagada',
            field=models.BooleanField(default=False, help_text='True cuando total_cobrado >= precio_venta', verbose_name='pagada'),
        ),
        migrations.AddField(
            model_name='ventavehiculo',
            name='total_cobrado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Actualizado automáticamente al recibir plazos', max_digits=10, verbose_name='total cobrado'),
        ),
        migrations.CreateModel(
            name='CobroFraccionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField(verbose_name='fecha de vencimiento')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='importe del plazo')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDO', 'Recibido')], default='PENDIENTE', max_length=15, verbose_name='estado')),
                ('tipo_financiacion', models.CharField(choices=[('CONTADO', 'Contado'), ('DIRECTA', 'Financiación Directa S.L.'), ('EXTERNA', 'Financiación Bancaria Externa')], default='CONTADO', max_length=10, verbose_name='tipo de financiación')),
                ('comision_financiera', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='comisión financiera')),
                ('numero_plazo', models.PositiveIntegerField(verbose_name='número de plazo')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banco_movimiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobro_fraccionado', to='bank.bancomovimiento', verbose_name='movimiento bancario')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='sales.ventavehiculo', verbose_name='venta')),
            ],
            options={
                'verbose_name': 'cobro fraccionado',
                'verbose_name_plural': 'cobros fraccionados',
                'ordering': ['fecha_vencimiento'],
                'unique_together': {('venta', 'numero_plazo')},
            },
        ),
    ]
