name: Respaldo Diario de PostgreSQL

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - name: Instalar herramientas de PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client

    - name: Realizar copia de seguridad (pg_dump)
      run: |
        pg_dump "${{ secrets.DATABASE_URL }}" -F c -b -v -f backup_django_$(date +%Y%m%d).sql

    - name: Subir respaldo a almacenamiento seguro
      uses: actions/upload-artifact@v4
      with:
        name: respaldo-postgres-${{ github.run_id }}
        path: backup_django_*.sql
        retention-days: 30
